AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cadê o Rolê backend

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getEvents
      Timeout: 30
      Runtime: nodejs6.10
      Events:
        GetEvents:
          Type: Api
          Properties:
            Path: /events
            Method: get
